### ISSUE TITLE
Inline database/table misalign with title

### ISSUE THREAD

**Issue by wuqiling97** [notion-enhancer/repo#44]
**What is happening?**

When I turn on "wrap tables to page width" in the "Tweaks" extension, and shrink width below 900px, inline database will have extra padding at left, misaligned with database title.

**What should be happening?**

inline database aligned with database title.

**Screenshots (if applicable):**

html width below 900px

<img width="679" alt="below 900px" src="https://user-images.githubusercontent.com/19304928/148058416-8c938cb0-5a0b-4b64-adde-7ba95225cfa4.png">

width above 900px

<img width="743" alt="above 900px" src="https://user-images.githubusercontent.com/19304928/148058427-4f1f4935-8973-40ac-8345-ed1772822644.png">

**Operating system/browser name & version:**

win10 21H1, build 19043.1415

**notion-enhancer and/or notion-repackaged version:**

notion-repackaged 2.0.18-1

**notion-enhancer configuration (enabled/disabled mods and their settings):**

Enabled mods:
tray
tweaks: responsive columns breakpoint 600px, 30%, wrap tables to page width

**Comment by wuqiling97** [comment]
possible solution: 

`repo/tweaks/client.css` line 23~35, add `!important` for padding

```css

.enhancer--tweak-normalise_table_scroll
  .notion-frame
  .notion-page-content
  .notion-collection_view-block,
.enhancer--tweak-normalise_table_scroll .notion-peek-renderer .notion-collection_view-block,
.enhancer--tweak-normalise_table_scroll
  .notion-page-template-modal
  .notion-collection_view-block,
.enhancer--tweak-normalise_table_scroll .notion-collection-view-body .notion-table-view {
  width: 100% !important;
  padding-left: 0 !important;
  padding-right: 0 !important;
}

```
