### ISSUE TITLE
How do I remove the space above the title of the page

### ISSUE THREAD

**Issue by Koushikphy** [notion-enhancer/repo#66]
When you open a new page but there is no cover picture, there is some space in between the top of the page and the title of the page. I don't want that space, I want any page title should be at the top of the page. Is there any way to remove that space?

**Comment by amv146** [comment]
`[class='notion-page-controls'][style*='margin-top: 80px;'] {
  margin-top: 20px !important;
}`


Put this into CSS tweaks file, you can change margin-top to any number of px, the default is 80px

**Comment by Koushikphy** [comment]
Well I did this 
```css
.notion-page-controls[style*='margin-top: 80px;']{
    margin-top: 0px !important; 
}
.notion-record-icon.notranslate.notion-focusable{
    margin-top: 0 !important;    
}
```
